namespace SHC_Rebalancer;

public enum Unit
{
    None,
    Peasant,
    BurningMan,
    Woodcutter,
    Fletcher,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Tunneler,
    Hunter,
    StoneMason,
    Goadman,
    Ox,
    Pitchman,
    WheatFarmer,
    HopFarmer,
    AppleFarmer,
    DairyFarmer,
    Miller,
    Baker,
    Brewer,
    Poleturner,
    Blacksmith,
    Armourer,
    Tanner,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    EuropArcher,
    [UnitCost]
    [UnitMeleeDamageToWalls]
    Crossbowman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    [UnitAlwaysRun]
    Spearman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Pikeman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    [UnitAlwaysRun]
    Maceman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Swordsman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Knight,
    [UnitCost]
    Ladderman,
    [UnitCost]
    Engineer,
    IronMiner,
    Porter,
    Priest,
    Healer,
    Drunkard,
    Innkeeper,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    [UnitAlwaysRun]
    Monk,
    Unknown38,
    Catapult,
    Trebuchet,
    Mangonel,
    Trader,
    HorseTrader,
    Deer,
    Lion,
    Rabbit,
    Camel,
    Crow,
    Seagull,
    Unknown50,
    Cow,
    Dog,
    Fireman,
    Ghost,
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Lord,
    Lady,
    Jester,
    SiegeTower,
    [UnitMeleeDamageToBuildings]
    BatteringRam,
    PortableShield,
    TowerBallista,
    Chicken,
    Mother,
    Child,
    Juggler,
    FireEater,
    WarDog,
    BurningBigAnimal,
    BurningSmallAnimal,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    ArabArcher,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    Slave,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Slinger,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Assassin,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    HorseArcher,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    ArabSwordsman,
    [UnitCost]
    [UnitMeleeDamageToBuildings]
    [UnitMeleeDamageToTowers]
    [UnitMeleeDamageToWalls]
    Firethrower,
    FireBallista,
    Unknown78,
    Unknown79,
}
